apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  namespace: node-app
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
    protocol: TCP
