apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  namespace: node-app
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80                 
    targetPort: 3000
  type: LoadBalancer
